
version: '3.4'

services:
  backend:
    container_name: backend
    env_file: .env
    user: ${CURRENT_UID}
    build:
      context: ./backend
      args:
        - DEBUG=${COMMON_DEBUG}
      target: deploy
    restart: on-failure
    entrypoint: ./docker-entrypoint.sh
    depends_on: 
      - postgres_db
    volumes:
      - ./backend:/app
    ports: 
      - 80:8000
    networks:
      private_network:

  postgres_db:
    container_name: postgres_db
    env_file: .env
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      private_network:

  pgadmin:
    container_name: pgadmin
    env_file: .env
    image: dpage/pgadmin4
    depends_on:
      - postgres_db
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    restart: on-failure
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      private_network:

  redis:
    image: "redis:5.0-alpine"
    container_name: redis
    hostname: redis
    user: ${CURRENT_UID}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: on-failure
    volumes:
      - redis_data:/data
    depends_on:
      - backend
    networks:
      private_network:

  redis-commander:
    container_name: redis-commander
    env_file: .env
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      private_network:

  worker:
    container_name: worker
    hostname: worker
    env_file: .env
    image: base-fastapi-postgresql_backend
    volumes:
      - ./backend:/app
    restart: on-failure
    command: arq app.worker.WorkerSettings
    depends_on:
      - redis
      - backend
      - postgres_db
    networks:
      private_network:


networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16


volumes:
  pgadmin_data:
  db_data:
  redis_data:
